CREATE TABLE `shard_config` (
  `ShardID` int NOT NULL AUTO_INCREMENT,
  `TenantID` char(36) DEFAULT NULL,
  `AppCode` varchar(20) DEFAULT NULL,
  `Server` varchar(50) DEFAULT NULL,
  `Port` int DEFAULT NULL COMMENT 'Cổng',
  `Database` varchar(50) DEFAULT NULL,
  `UserID` varchar(50) DEFAULT NULL,
  `Password` varchar(50) DEFAULT NULL,
  `VersionDB` varchar(255) DEFAULT NULL COMMENT 'Phiên bản db hiện tại',
  `Env` char(20) DEFAULT 'g2' COMMENT 'Môi trường hiện tại của dữ liệu',
  `Status` int NOT NULL DEFAULT '0' COMMENT 'Trạng thái dữ liệu 0: làm việc, 1- không làm việc',
  `CreatedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`ShardID`),
  KEY `FK_shard_config_application_ApplicationCode` (`AppCode`),
  KEY `FK_shard_config_tenant_TenantID` (`TenantID`),
  CONSTRAINT `FK_shard_config_tenant_TenantID` FOREIGN KEY (`TenantID`) REFERENCES `tenant` (`TenantID`)
) ENGINE=InnoDB AUTO_INCREMENT=177471;

CREATE TABLE `sys_msc_user` (
  `UserID` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci NOT NULL COMMENT 'Khóa chính bảng quản lý người dùng, khóa này là trườn user_id bên amis',
  `Inactive` tinyint NOT NULL DEFAULT '0' COMMENT 'Trạng thái hoạt động người dùng true: ngừng hoạt động, false: hoạt động bt',
  `FullName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Tên đầy đủ người dùng',
  `Email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Email người dùng',
  `MobilePhone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Số điện thoại người dùng',
  `MisaID` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci NOT NULL COMMENT 'misa_id của người dùng',
  `AmisRoleType` int DEFAULT NULL COMMENT 'Vai trò của người dùng bên Amis platform',
  `CreatedBy` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Người tạo',
  `CreatedDate` datetime DEFAULT NULL COMMENT 'Ngày tạo',
  `ModifiedBy` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Người sửa đổi',
  `ModifiedDate` datetime DEFAULT NULL COMMENT 'Ngày thay đổi',
  `IsConfirmEmail` tinyint DEFAULT '1' COMMENT 'Đã xác nhận mail bên Amis platform hay chưa',
  `OrganizationUnitID` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'ID Đơn vị công tác',
  `OrganizationUnitName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Tên Đơn vị công tác',
  PRIMARY KEY (`UserID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_ci AVG_ROW_LENGTH=4096 COMMENT='Bảng quản lý người dùng'

CREATE TABLE `di_inventory_item` (
  `InventoryItemID` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci NOT NULL COMMENT 'Khóa chính của bảng',
  `ReleaseMethod` int DEFAULT '1' COMMENT 'Phương pháp xuất kho ngầm định là FIFO',
  `UnitID` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Đơn vị tính chính',
  `UnitName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Tên đơn vị tính',
  `InventoryItemCode` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL,
  `InventoryItemName` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci NOT NULL COMMENT 'Tên VTHH',
  `InventoryItemType` int NOT NULL DEFAULT '0' COMMENT 'Loại VTHH: 0- hàng hóa, 1- nguyên vật liệu, 2- thành phẩm',
  `InventoryItemCategoryIDList` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Danh sách id nhóm VTHH',
  `InventoryItemCategoryCodeList` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Danh sách Mã nhóm VTHH',
  `InventoryItemCategoryNameList` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Danh sách tên nhóm VTHH',
  `MaximumStock` decimal(24,10) NOT NULL DEFAULT '0.0000000000' COMMENT 'Số lượng tồn kho tối đa',
  `MinimumStock` decimal(24,10) NOT NULL DEFAULT '0.0000000000' COMMENT 'Số lượng tồn kho tối đa',
  `QuantityBalance` decimal(24,10) NOT NULL DEFAULT '0.0000000000' COMMENT 'Số lượng tồn kho',
  `WarrantyTimeUnit` int DEFAULT NULL COMMENT 'Đơn vị thời gian bảo hành (3: năm, 2: tháng, 1: ngày)',
  `InventoryItemSource` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Nguồn gốc',
  `Description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Mô tả',
  `Image` varchar(1028) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Ảnh vật tư hàng hóa',
  `Inactive` tinyint DEFAULT '0' COMMENT 'Trạng thái hoạt động: true-không hoạt động',
  `UnitList` json DEFAULT NULL COMMENT 'Đơn vị chuyển đổi',
  `BuyPrice` decimal(24,10) NOT NULL DEFAULT '0.0000000000' COMMENT 'Giá mua',
  `SellPrice` decimal(24,10) NOT NULL DEFAULT '0.0000000000' COMMENT 'Giá bán',
  `BackEndFormula` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Công thức backend',
  `FrontEndFormula` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Công thức frontend',
  `DICustomField1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Trường mở rộng 1',
  `DICustomField2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Trường mở rộng 2',
  `DICustomField3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Trường mở rộng 3',
  `DICustomField4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Trường mở rộng 4',
  `DICustomField5` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Trường mở rộng 5',
  `DICustomField6` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Trường mở rộng 6',
  `DICustomField7` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Trường mở rộng 7',
  `DICustomField8` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Trường mở rộng 8',
  `DICustomField9` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Trường mở rộng 9',
  `DICustomField10` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Trường mở rộng 10',
  `CreatedDate` datetime DEFAULT NULL COMMENT 'Ngày tạo',
  `CreatedBy` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL,
  `ModifiedDate` datetime DEFAULT NULL COMMENT 'Ngày sửa',
  `ModifiedBy` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL,
  `IsFollowSerialNumber` tinyint DEFAULT '0' COMMENT 'Vật tư hàn hóa có theo dõi theo mã quy cách không',
  `IsAllowDuplicateSerialNumber` tinyint DEFAULT '0' COMMENT 'True: nếu tất cả mã quy cách cho trùng, ngược lại false',
  `WarrantyTime` decimal(24,0) DEFAULT NULL COMMENT 'Thời gian bảo hành',
  `BaseOnFormula` int DEFAULT NULL COMMENT 'Cột dựa trên cách tính',
  `SyncID` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'ID đồng bộ danh mục',
  `SyncBranchID` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'ID chi nhánh đồng bộ',
  `InventoryDefaultStockIDList` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Danh sách ID kho ngầm định',
  `InventoryDefaultStockNameList` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Danh sách tên kho ngầm định',
  `InventoryDefaultLocationIDList` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Danh sách ID vị trí ngầm định',
  `InventoryDefaultLocationCodeList` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Danh sách mã vị trí ngầm định',
  `QuantityAvailable` decimal(24,10) DEFAULT '0.0000000000' COMMENT 'Số lượng tồn khả dụng',
  `InventoryCombo` json DEFAULT NULL COMMENT 'Thông tin combo vật tư dưới dạng JSON',
  PRIMARY KEY (`InventoryItemID`),
  KEY `ix_diinventoryitem_inventoryitemcode` (`InventoryItemCode`),
  KEY `ix_diinventoryitem_inventoryitemname` (`InventoryItemName`),
  KEY `ix_diinventoryitem_lowerinventoryitemcode` ((lower(`InventoryItemCode`))),
  KEY `ix_diinventoryitem_syncid_lowercode1` (`SyncID`,(lower(`InventoryItemCode`)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_ci AVG_ROW_LENGTH=1024 COMMENT='Danh mục vật tư hàng hóa';

CREATE TABLE `di_stock` (
  `StockID` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci NOT NULL COMMENT 'Khóa chính của bảng',
  `Inactive` tinyint NOT NULL DEFAULT '0' COMMENT 'Trạng thái danh mục false: đang sử dụng, true: ngừng sử dụng',
  `StockCode` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Mã kho',
  `StockName` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Tên kho',
  `Country` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Quốc gia',
  `ProvinceOrCity` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Tỉnh/ Thành phố',
  `District` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Quận/ Huyện',
  `WardOrCommune` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Xã/ Phường',
  `Address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Địa chỉ',
  `ListOrganizationUnitID` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'List ID chi nhánh',
  `ListOrganizationUnitName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'List tên chi nhánh',
  `CreatedBy` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Người tạo',
  `CreatedDate` datetime DEFAULT NULL COMMENT 'Ngày tạo',
  `ModifiedBy` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Người sửa đổi',
  `ModifiedDate` datetime DEFAULT NULL COMMENT 'Ngày thay đổi',
  `StreetName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci COMMENT 'Số nhà/Tên đường',
  `SyncID` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'ID đồng bộ danh mục',
  `AccountingStockCode` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'Mã kho kế toán',
  `SortOrder` int DEFAULT NULL COMMENT 'Thứ tự sắp xếp',
  `SyncBranchID` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci DEFAULT NULL COMMENT 'ID chi nhánh đồng bộ',
  PRIMARY KEY (`StockID`),
  KEY `ix_distock_syncid` (`SyncID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_ci AVG_ROW_LENGTH=4096 COMMENT='Bảng danh mục kho';